import { sql } from 'drizzle-orm';
import type { EntityId } from '../../shared/domain';
import type { AppDatabase } from './client';

/**
 * UUID v4 for new entities, generated by the app (never AUTOINCREMENT) so it can be synced later.
 * Hermes in this project exposes no `crypto` (verified on the Android emulator), so the 16 random
 * bytes come from SQLite's randomblob(), a CSPRNG seeded by the OS, instead of adding a dependency.
 */
export async function generateId(db: AppDatabase): Promise<EntityId> {
  const row = await db.get<[string]>(sql`SELECT lower(hex(randomblob(16)))`);
  return formatUuidV4(row[0]);
}

/** Formats 32 random hex digits as a UUID v4 (sets the version and RFC 4122 variant bits). */
export function formatUuidV4(hex: string): EntityId {
  // RFC 4122 variant: the 17th digit becomes 8, 9, a or b (keeps its two random low bits).
  const variant = '89ab'[parseInt(hex[16], 16) % 4];
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    `4${hex.slice(13, 16)}`,
    `${variant}${hex.slice(17, 20)}`,
    hex.slice(20, 32),
  ].join('-');
}
