import { sql } from 'drizzle-orm';
import { nowIsoDateTime } from '../../shared/lib/dates';
import type { Database } from './client';

/** Shape of migrations/migrations.js generated by drizzle-kit (driver: 'expo'). */
export type MigrationBundle = {
  journal: { entries: readonly { idx: number; tag: string }[] };
  migrations: Record<string, string>;
};

const STATEMENT_BREAKPOINT = '--> statement-breakpoint';
const FOREIGN_KEYS_PRAGMA = /^PRAGMA\s+foreign_keys\s*=\s*(ON|OFF)\s*;?$/i;

/**
 * Applies pending drizzle-kit migrations, each one atomically, and records them in
 * `schema_migrations`. Idempotent: applied migrations are skipped by their journal idx.
 *
 * A migration that recreates tables (drizzle-kit emits PRAGMA foreign_keys=OFF/ON) gets
 * foreign keys disabled BEFORE BEGIN, since the pragma is a no-op inside a transaction,
 * `PRAGMA foreign_key_check` before COMMIT, and foreign keys re-enabled afterwards.
 */
export async function migrate(
  database: Database,
  bundle: MigrationBundle,
): Promise<void> {
  const { db } = database;

  await db.run(sql`CREATE TABLE IF NOT EXISTS schema_migrations (
    idx INTEGER PRIMARY KEY NOT NULL,
    tag TEXT NOT NULL,
    applied_at TEXT NOT NULL
  )`);

  const applied = await db.values<[number]>(
    sql`SELECT idx FROM schema_migrations`,
  );
  const appliedIdx = new Set(applied.map(([idx]) => idx));

  const pending = [...bundle.journal.entries]
    .filter(entry => !appliedIdx.has(entry.idx))
    .sort((a, b) => a.idx - b.idx);

  for (const entry of pending) {
    const key = `m${entry.idx.toString().padStart(4, '0')}`;
    const content = bundle.migrations[key];
    if (content === undefined) {
      throw new Error(`Missing SQL for migration ${entry.tag} (${key})`);
    }

    const statements = content
      .split(STATEMENT_BREAKPOINT)
      .map(statement => statement.trim())
      .filter(statement => statement.length > 0);
    const disablesForeignKeys = statements.some(statement =>
      /^PRAGMA\s+foreign_keys\s*=\s*OFF/i.test(statement),
    );
    const body = statements.filter(
      statement => !FOREIGN_KEYS_PRAGMA.test(statement),
    );

    if (disablesForeignKeys) {
      await db.run(sql`PRAGMA foreign_keys = OFF`);
    }
    try {
      await database.withTransaction(async tx => {
        for (const statement of body) {
          await tx.run(sql.raw(statement));
        }
        if (disablesForeignKeys) {
          const violations = await tx.values(sql`PRAGMA foreign_key_check`);
          if (violations.length > 0) {
            throw new Error(
              `Migration ${entry.tag} leaves ${violations.length} foreign key violation(s)`,
            );
          }
        }
        await tx.run(
          sql`INSERT INTO schema_migrations (idx, tag, applied_at) VALUES (${
            entry.idx
          }, ${entry.tag}, ${nowIsoDateTime()})`,
        );
      });
    } finally {
      if (disablesForeignKeys) {
        await db.run(sql`PRAGMA foreign_keys = ON`);
      }
    }
  }
}
